[project]
name = "hiver-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "groq>=1.7.0",
    "numpy>=2.5.3",
    "openai>=3.11.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.1",
]
